name: Lint

on:
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'tests/**'
      - 'requirements.txt'
      - '.github/workflows/lint.yml'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release tag
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236
        with:
          python-version: '3.10'

      - name: Lint
        run: |
          pip install pipenv
          pipenv install -d
          pipenv run make lint